// Mock data for admin dashboard
export const adminMetrics = {
  totalUsers: 15420,
  totalTransactions: 89650,
  pendingKYC: 234,
  activeLoans: 1250,
  totalDeposits: 45600000,
  totalWithdrawals: 32100000,
  userGrowth: [
    { month: "Jan", users: 8500 },
    { month: "Feb", users: 9200 },
    { month: "Mar", users: 10100 },
    { month: "Apr", users: 11500 },
    { month: "May", users: 13200 },
    { month: "Jun", users: 15420 },
  ],
  transactionVolume: [
    { month: "Jan", volume: 65000 },
    { month: "Feb", volume: 72000 },
    { month: "Mar", volume: 78000 },
    { month: "Apr", volume: 82000 },
    { month: "May", users: 86000 },
    { month: "Jun", volume: 89650 },
  ],
}

export const adminUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@email.com",
    phone: "+237 6XX XXX XXX",
    type: "personal",
    kycStatus: "approved",
    accountStatus: "active",
    balance: 250000,
    joinDate: "2024-01-15",
    lastLogin: "2024-06-20",
  },
  {
    id: "2",
    name: "TechCorp Ltd",
    email: "admin@techcorp.com",
    phone: "+237 6XX XXX XXX",
    type: "business",
    kycStatus: "pending",
    accountStatus: "active",
    balance: 1500000,
    joinDate: "2024-02-10",
    lastLogin: "2024-06-19",
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane.smith@email.com",
    phone: "+237 6XX XXX XXX",
    type: "personal",
    kycStatus: "rejected",
    accountStatus: "frozen",
    balance: 75000,
    joinDate: "2024-03-05",
    lastLogin: "2024-06-18",
  },
]

export const adminTransactions = [
  {
    id: "TXN001",
    userId: "1",
    userName: "John Doe",
    type: "transfer",
    amount: 50000,
    status: "completed",
    date: "2024-06-20",
    description: "Transfer to Jane Smith",
    flagged: false,
  },
  {
    id: "TXN002",
    userId: "2",
    userName: "TechCorp Ltd",
    type: "deposit",
    amount: 500000,
    status: "pending",
    date: "2024-06-20",
    description: "Business deposit",
    flagged: true,
  },
  {
    id: "TXN003",
    userId: "3",
    userName: "Jane Smith",
    type: "withdrawal",
    amount: 25000,
    status: "completed",
    date: "2024-06-19",
    description: "ATM withdrawal",
    flagged: false,
  },
]

export const adminLoans = [
  {
    id: "LOAN001",
    userId: "1",
    userName: "John Doe",
    type: "personal",
    amount: 500000,
    status: "pending",
    purpose: "Home renovation",
    repaymentPeriod: 24,
    applicationDate: "2024-06-15",
    monthlyPayment: 25000,
  },
  {
    id: "LOAN002",
    userId: "2",
    userName: "TechCorp Ltd",
    type: "business",
    amount: 2000000,
    status: "approved",
    purpose: "Equipment purchase",
    repaymentPeriod: 36,
    applicationDate: "2024-06-10",
    monthlyPayment: 65000,
  },
]

export const adminPartners = [
  {
    id: "1",
    name: "MTN Cameroon",
    type: "Telecom",
    status: "active",
    services: ["Mobile Money", "Airtime"],
    integrationDate: "2024-01-01",
  },
  {
    id: "2",
    name: "ENEO",
    type: "Utility",
    status: "active",
    services: ["Electricity Bills"],
    integrationDate: "2024-02-15",
  },
  {
    id: "3",
    name: "Afriland First Bank",
    type: "Bank",
    status: "inactive",
    services: ["External Transfers"],
    integrationDate: "2024-03-01",
  },
]

export const adminAlerts = [
  {
    id: "ALT001",
    type: "suspicious_transaction",
    severity: "high",
    userId: "2",
    userName: "TechCorp Ltd",
    description: "Large deposit exceeding normal pattern",
    amount: 500000,
    date: "2024-06-20",
    status: "pending",
  },
  {
    id: "ALT002",
    type: "multiple_failed_logins",
    severity: "medium",
    userId: "3",
    userName: "Jane Smith",
    description: "Multiple failed login attempts",
    date: "2024-06-19",
    status: "investigated",
  },
]
